version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  

#       version: 3
# services:
#     web:
#       build: .
#       port: 
#         - "5000:5000"
#       volumes: 
#         - /opt/mysqlFlaskDocker:/mysqlFlaskDocker
#       links:
#         - db:mysql
#       container_name: containerapp_web_1
#       dependson: 
#         - db 
#     db:
#       image: mysql:5.7
#       restart: always
#       container_name: countainerapp_db_1
#       environment: 
#         MYSQL_ROOT_PASSWORD: rootpass
#         MYSQL_DATABASE: counter

  
  
  

  # redis:
  #   image: "redis:alpine"

    
# version: '3'
# services:
#   web:
#     volumes:
#       - ./app:/app
#     ports:
#       - "80:80"
    
#     # command: flask run --host=0.0.0.0 --port=80
#     # Infinite loop, to keep it alive, for debugging
#     # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"